name       : par2cmdline
version    : 0.6.14
release    : 1
source     :
    - https://github.com/Parchive/par2cmdline/archive/v0.6.14.tar.gz : 2fd831ba924d9f0ecd9242ca45551b6995ede1ed281af79aa30e7490d5596e7a
license    : GPL-2.0
component  : programming.tools
summary    : PAR file verification and repair tool
description: |
    par2cmdline is a program for creating and using PAR2 files to detect damage in data files and repair them if necessary. It can be used with any kind of file.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
