name       : par2cmdline
version    : 0.8.0
release    : 2
source     :
    - https://github.com/Parchive/par2cmdline/releases/download/v0.8.0/par2cmdline-0.8.0.tar.bz2 : 496430e185f2d82e54245a0554341a1826f06c5e673fa12a10f176c7f9b42964
license    : GPL-2.0-or-later
component  : programming.tools
summary    : PAR file verification and repair tool
description: |
    par2cmdline is a program for creating and using PAR2 files to detect damage in data files and repair them if necessary. It can be used with any kind of file.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
