name       : par2cmdline
version    : 0.8.1
release    : 3
source     :
    - https://github.com/Parchive/par2cmdline/releases/download/v0.8.1/par2cmdline-0.8.1.tar.bz2 : 5fcd712cae2b73002b0bf450c939b211b3d1037f9bb9c3ae52d6d24a0ba075e4
license    : GPL-2.0-or-later
component  : programming.tools
summary    : PAR file verification and repair tool
description: |
    par2cmdline is a program for creating and using PAR2 files to detect damage in data files and repair them if necessary. It can be used with any kind of file.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
